enum KolkhozText {
  lobbyCreateGame,
  lobbyPlayDemo,
  lobbyJoinGame,
  lobbyHowToPlay,
  lobbyAccountStatus,
  lobbyLanguage,
  lobbyTheme,
  lobbySettings,
  presetKolkhoz,
  presetLittleKolkhoz,
  presetCampStyle,
  presetCustom,
  variantDeck52Cards,
  variantDeck36Cards,
  variantDeckLabel,
  variantValue1CardDeck,
  variantValue1YearPlan,
  variantNomenklaturaTitle,
  variantNomenklaturaDescription,
  variantSwapTitle,
  variantSwapDescription,
  variantNorthernStyleTitle,
  variantNorthernStyleDescription,
  variantMiceTitle,
  variantMiceDescription,
  variantOrdenNachalnikuTitle,
  variantOrdenNachalnikuDescription,
  variantMedalsTitle,
  variantMedalsDescription,
  variantHeroTitle,
  variantHeroDescription,
  variantAccumulationTitle,
  variantAccumulationDescription,
  variantWreckerTitle,
  variantWreckerDescription,
  variantDemoModeTitle,
  variantDemoModeDescription,
  appsettingsDark,
  appsettingsLight,
  appsettingsSwitchToLightMode,
  appsettingsSwitchToDarkMode,
  appsettingsCardBacks,
  appsettingsClassic,
  appsettingsHarvest,
  appsettingsGranary,
  appsettingsWinter,
  tabledisplayYou,
  tutorialdisplayBack,
  tutorialdisplayDone,
  tutorialdisplayNext,
  tutorialdisplayForemanMisha,
  tutorialdisplayTip,
  tutorialdisplayDoneWellWorkedComrade,
  boardviewPassDevice,
  boardviewSeatValue1IsUp,
  boardviewReady,
  boardviewYourTurn,
  boardviewWait,
  boardviewFamineYear,
  boardviewChooseTrump,
  lowerbaractionsSwap,
  lowerbaractionsUndo,
  lowerbaractionsConfirm,
  lowerbaractionsFinish,
  lowerbaractionsYearValue1,
  phasedisplayYearValue1Phasename,
  kolkhozappCancel,
  kolkhozappNewGame,
  kolkhozappThisWillReplaceTheCurrentGame,
  kolkhozappNewGame2,
  kolkhozappMainMenu,
  kolkhozappLeaveTheCurrentGameAndReturnToSetup,
  kolkhozappMainMenu2,
  kolkhozappRememberYouMustFollowSuitIfAble,
  kolkhozappSignedInProfileLoaded,
  kolkhozappAccountCreatedCheckYourEmailToConfirmItThe,
  kolkhozappAccountCreated,
  kolkhozappSignedOut,
  kolkhozappPasswordResetEmailSent,
  kolkhozappSyncingProfile,
  kolkhozappProfileSaved,
  kolkhozappProfileLoaded,
  kolkhozappAccountRequestFailed,
  kolkhozappProfileSyncFailed,
  kolkhozappSignInBeforeJoiningOnlinePlay,
  kolkhozappOnlineSignInExpiredSignInAgain,
  kolkhozappCouldNotVerifyOnlineAccountTryAgain,
  kolkhozappCloudAccountUnavailable,
  kolkhozappConnectingAccount,
  kolkhozappSignedInEmail,
  kolkhozappSignedIn,
  kolkhozappSignedOut2,
  kolkhozappGameBy,
  kolkhozappWilliamTheisen,
  kolkhozappProfile,
  kolkhozappSettings,
  kolkhozappProgress,
  kolkhozappCouldNotReachTheOnlineServerTryAgainInAMom,
  kolkhozappOnlineRequestFailedTryAgain,
  kolkhozappDemoMode2YearKolkhozWithEasyAi,
  kolkhozappWorking,
  kolkhozappStartDemo,
  kolkhozappStartOnlineGame,
  kolkhozappStartOfflineGame,
  kolkhozappContinueToLobby,
  kolkhozappBackToSetup,
  kolkhozappSaveFavorite,
  kolkhozappUseFavorite,
  kolkhozappFavoriteSaved,
  kolkhozappRanked,
  kolkhozappLocked,
  kolkhozappBrowser,
  kolkhozappAccess,
  kolkhozappComrades,
  kolkhozappYourComradeCode,
  kolkhozappComradeCode,
  kolkhozappAddComrade,
  kolkhozappRemove,
  kolkhozappNoComrades,
  kolkhozappComradeAdded,
  kolkhozappComradeRequestSent,
  kolkhozappComrade,
  kolkhozappNotComrade,
  kolkhozappPending,
  kolkhozappIncomingRequests,
  kolkhozappOutgoingRequests,
  kolkhozappNoComradeRequests,
  kolkhozappAccept,
  kolkhozappDecline,
  kolkhozappComradeRequestAccepted,
  kolkhozappComradeRequestDeclined,
  kolkhozappComradeRemoved,
  kolkhozappGameInvite,
  kolkhozappValue1InvitedYouToAGame,
  kolkhozappOfflineStatus,
  kolkhozappInGame,
  kolkhozappInLobby,
  kolkhozappCasual,
  kolkhozappGameType,
  kolkhozappPValue1,
  kolkhozappHotseat,
  kolkhozappOnline,
  kolkhozappDecktypeCardsMaxyearsYears,
  kolkhozappHowToPlay,
  kolkhozappTutorial,
  kolkhozappProfile2,
  kolkhozappDisplayName,
  kolkhozappPortrait,
  kolkhozappPasswordsDoNotMatch,
  kolkhozappCloudProfilesAreNotConfiguredForThisBuild,
  kolkhozappCloudProfilesAreStarting,
  kolkhozappSignedInAsValue1,
  kolkhozappSignInToSyncProfileAndOnlineSeats,
  kolkhozappAccount,
  kolkhozappEmail,
  kolkhozappPassword,
  kolkhozappConfirmPassword,
  kolkhozappSignIn,
  kolkhozappReset,
  kolkhozappCreate,
  kolkhozappSignOut,
  kolkhozappOffline,
  kolkhozappGames,
  kolkhozappOffWins,
  kolkhozappWins,
  kolkhozappOnline2,
  kolkhozappOnWins,
  kolkhozappCasualRating,
  kolkhozappRankedRating,
  kolkhozappRating,
  kolkhozappCurrent,
  kolkhozappWins2,
  kolkhozappTotal,
  kolkhozappLosses,
  kolkhozappStats,
  kolkhozappNoOpenGames,
  kolkhozappValue1Open,
  kolkhozappValue1CitizensOnline,
  kolkhozappRefreshInValue1s,
  kolkhozappJoinedValue1,
  kolkhozappSentNorthOnlinePlayIsLockedForThisAccount,
  kolkhozappTheOnlineServerRejectedTheRequest,
  kolkhozappOnlinePlay,
  kolkhozappJoinAnOpenGameOrEnterAnInviteCode,
  kolkhozappInviteCode,
  kolkhozappYourInviteCode,
  kolkhozappWaitingForPlayers,
  kolkhozappGameStartsInValue1s,
  kolkhozappSearchingForPlayer,
  kolkhozappCopyCode,
  kolkhozappCopyResult,
  kolkhozappCopied,
  kolkhozappJoinGame,
  kolkhozappAssignGame,
  kolkhozappKick,
  kolkhozappOpenGames,
  kolkhozappRefresh,
  kolkhozappOpenOpenseats,
  kolkhozappHost,
  kolkhozappSeats,
  kolkhozappTurn,
  kolkhozappMoves,
  kolkhozappWaiting,
  kolkhozappOpen,
  kolkhozappAverageRating,
  kolkhozappPlayer,
  kolkhozappScore,
  kolkhozappMedals,
  kolkhozappHand,
  kolkhozappCellar,
  kolkhozappPlot,
  kolkhozappController,
  kolkhozappBrigadeLeader,
  kolkhozappCurrentTurn,
  kolkhozappAny,
  kolkhozappHuman,
  kolkhozappEasy,
  kolkhozappMedium,
  kolkhozappHard,
  plotdisplayOtherStoresAboveActivePlayerSCellarBelow,
  plotdisplayAllJobsComplete,
  plotdisplayAuditComplete,
  boardOptionspanelInstant,
  boardOptionspanelFast,
  boardOptionspanelNormal,
  boardOptionspanelSlow,
  boardOptionspanelSession,
  boardOptionspanelAssist,
  boardOptionspanelDisplay,
  boardOptionspanelRules,
  boardOptionspanelMenu,
  boardOptionspanelGameControls,
  boardOptionspanelHowToPlay,
  boardOptionspanelSafeguards,
  boardOptionspanelConfirmNewGame,
  boardOptionspanelAskBeforeReplacingTheCurrentGame,
  boardOptionspanelConfirmMainMenu,
  boardOptionspanelAskBeforeLeavingTheCurrentGame,
  boardOptionspanelMoveHelp,
  boardOptionspanelInvalidTapHints,
  boardOptionspanelShowTheForemanReminderWhenYouTapAnIllegalC,
  boardOptionspanelAnimationSpeed,
  boardPlotpanelRequisition,
  boardPlotpanelPrivatePlot,
  boardPlotpanelGameOver,
  boardPlotpanelWinnerWinnernameWinnerscore,
  boardHandtrayUndo,
  boardHandtrayPlay,
  handConsoleYourTurnToPlay,
  handConsoleChooseSwap,
  handConsoleAssignTrick,
  handConsoleReviewRequisition,
  handConsoleWaitingForValue1,
  handConsoleWaitingForValue1ToPlay,
  handConsoleWaitingForValue1ToSwap,
  handConsoleWaitingForValue1ToAssign,
  handConsoleContinue,
  boardJobspanelDone,
  boardJobspanelTapToAssign,
  boardBoardrailBoard,
  boardBoardrailJobs,
  boardBoardrailNorth,
  boardBoardrailCellar,
  boardBoardrailLang,
  boardBoardrailBrigade,
  boardBoardrailTheNorth,
  ruleSummary1Title,
  ruleSummary1Body,
  ruleSummary2Title,
  ruleSummary2Body,
  ruleSummary3Title,
  ruleSummary3Body,
  ruleSummary4Title,
  ruleSummary4Body,
  ruleSummary5Title,
  ruleSummary5Body,
  ruleSummary6Title,
  ruleSummary6Body,
  ruleSummary7Title,
  ruleSummary7Body,
  ruleSummary8Title,
  ruleSummary8Body,
  tutorialStep1Title,
  tutorialStep1Body,
  tutorialStep1Tip,
  tutorialStep1Callout,
  tutorialStep2Title,
  tutorialStep2Body,
  tutorialStep2Tip,
  tutorialStep2Callout,
  tutorialStep3Title,
  tutorialStep3Body,
  tutorialStep3Tip,
  tutorialStep3Callout,
  tutorialStep4Title,
  tutorialStep4Body,
  tutorialStep4Tip,
  tutorialStep4Callout,
  tutorialStep5Title,
  tutorialStep5Body,
  tutorialStep5Tip,
  tutorialStep5Callout,
  tutorialStep6Title,
  tutorialStep6Body,
  tutorialStep6Tip,
  tutorialStep6Callout,
  tutorialStep7Title,
  tutorialStep7Body,
  tutorialStep7Tip,
  tutorialStep7Callout,
  tutorialStep8Title,
  tutorialStep8Body,
  tutorialStep8Tip,
  tutorialStep8Callout,
  tutorialStep9Title,
  tutorialStep9Body,
  tutorialStep9Tip,
  tutorialStep9Callout,
  tutorialStep10Title,
  tutorialStep10Body,
  tutorialStep10Tip,
  tutorialStep10Callout,
  tutorialStep11Title,
  tutorialStep11Body,
  tutorialStep11Tip,
  tutorialStep11Callout,
  tutorialStep12Title,
  tutorialStep12Body,
  tutorialStep12Tip,
  tutorialStep12Callout,
  tutorialStep13Title,
  tutorialStep13Body,
  tutorialStep13Tip,
  tutorialStep13Callout,
  suitWheat,
  suitSunflower,
  suitPotatoes,
  suitBeets,
  phasePlanning,
  phaseSwap,
  phaseTrick,
  phaseAssignment,
  phaseRequisition,
  phaseGameOver,
  languageSwitchTitle,
}

const Map<KolkhozText, ({String en, String ru})> kolkhozText = {
  KolkhozText.lobbyCreateGame: (en: 'Create Game', ru: 'Создать игру'),
  KolkhozText.lobbyPlayDemo: (en: 'Play Demo', ru: 'Играть демо'),
  KolkhozText.lobbyJoinGame: (en: 'Join Game', ru: 'Войти в игру'),
  KolkhozText.lobbyHowToPlay: (en: 'How to Play', ru: 'Как играть'),
  KolkhozText.lobbyAccountStatus: (en: 'Account status', ru: 'Аккаунт'),
  KolkhozText.lobbyLanguage: (en: 'Language', ru: 'Язык'),
  KolkhozText.lobbyTheme: (en: 'Theme', ru: 'Тема'),
  KolkhozText.lobbySettings: (en: 'Settings', ru: 'Настройки'),
  KolkhozText.presetKolkhoz: (en: 'Kolkhoz', ru: 'Колхоз'),
  KolkhozText.presetLittleKolkhoz: (en: 'Little Kolkhoz', ru: 'Колхозик'),
  KolkhozText.presetCampStyle: (en: 'Camp Style', ru: 'Лагерный'),
  KolkhozText.presetCustom: (en: 'Custom', ru: 'Свой'),
  KolkhozText.variantDeck52Cards: (en: '52 cards', ru: '52 карты'),
  KolkhozText.variantDeck36Cards: (en: '36 cards', ru: '36 карт'),
  KolkhozText.variantDeckLabel: (en: 'DECK', ru: 'КОЛОДА'),
  KolkhozText.variantValue1CardDeck: (
    en: '{value1} Card Deck',
    ru: 'Колода {value1} карт',
  ),
  KolkhozText.variantValue1YearPlan: (
    en: '{value1} Year Plan',
    ru: 'План на {value1} лет',
  ),
  KolkhozText.variantNomenklaturaTitle: (
    en: 'The Party lives by its own rules',
    ru: 'Номенклатура живёт по своим законам',
  ),
  KolkhozText.variantNomenklaturaDescription: (
    en: 'Trump face cards have special effects: Jack goes north, Queen exposes all, King doubles exile.',
    ru: 'Козырные фигуры имеют особые силы: Валет ссылается, Дама раскрывает всех, Король удваивает ссылку.',
  ),
  KolkhozText.variantSwapTitle: (
    en: 'Exchange Soap for an Awl',
    ru: 'Замените мыло на шило',
  ),
  KolkhozText.variantSwapDescription: (
    en: 'Exchange cards between your hand and plot at the start of each year.',
    ru: 'Обменивайте карты между рукой и участком в начале каждого года.',
  ),
  KolkhozText.variantNorthernStyleTitle: (
    en: 'Playing the Northern Way',
    ru: 'Игра по-северному',
  ),
  KolkhozText.variantNorthernStyleDescription: (
    en: 'No rewards for completed jobs - nobody earns protection.',
    ru: 'Нет наград за работы - все остаются уязвимы.',
  ),
  KolkhozText.variantMiceTitle: (
    en: 'They even talked to the mice',
    ru: 'Разговоры вели даже с мышами',
  ),
  KolkhozText.variantMiceDescription: (
    en: 'At requisition, every hidden plot is gnawed open.',
    ru: 'Все игроки раскрывают весь участок при реквизиции.',
  ),
  KolkhozText.variantOrdenNachalnikuTitle: (
    en: 'Medal to the Boss, the work to us',
    ru: 'Орден — начальнику, работа — нам',
  ),
  KolkhozText.variantOrdenNachalnikuDescription: (
    en: 'Finished jobs pile their cards into bonus rewards.',
    ru: 'Карты, назначенные на выполненные работы, копятся как награды.',
  ),
  KolkhozText.variantMedalsTitle: (
    en: 'Medals to fill a wardrobe but nothing to eat',
    ru: 'Орденов — полшкафа, а есть — нечего',
  ),
  KolkhozText.variantMedalsDescription: (
    en: 'Trick victories become medals on the final tally.',
    ru: 'Победы во взятках идут в итоговый счёт.',
  ),
  KolkhozText.variantHeroTitle: (
    en: 'Hero of Socialist Labor',
    ru: 'стахановец',
  ),
  KolkhozText.variantHeroDescription: (
    en: 'Win every trick in a year: you are protected and every other player is vulnerable.',
    ru: 'Выиграйте все взятки за год: вы защищены, а все остальные уязвимы для реквизиции.',
  ),
  KolkhozText.variantAccumulationTitle: (
    en: 'In the Common Pot',
    ru: 'НАКОПЛЕНИЕ',
  ),
  KolkhozText.variantAccumulationDescription: (
    en: 'Unclaimed job rewards stay in the pot for next year.',
    ru: 'Невостребованные награды за работы переносятся на следующий год.',
  ),
  KolkhozText.variantWreckerTitle: (en: 'Enemy of the People', ru: 'ВРЕДИТЕЛЬ'),
  KolkhozText.variantWreckerDescription: (
    en: 'Add a 14-value all-suit face card that wrecks its job at requisition.',
    ru: 'Добавляет фигуру со значением 14: она считается всеми мастями и проваливает свою работу при реквизиции.',
  ),
  KolkhozText.variantDemoModeTitle: (en: 'Demo Mode', ru: 'ДЕМО-РЕЖИМ'),
  KolkhozText.variantDemoModeDescription: (
    en: '2-year Kolkhoz with easy AI',
    ru: 'Колхоз на 2 года с лёгким ИИ',
  ),
  KolkhozText.appsettingsDark: (en: 'DARK', ru: 'ТЬМА'),
  KolkhozText.appsettingsLight: (en: 'LIGHT', ru: 'СВЕТ'),
  KolkhozText.appsettingsSwitchToLightMode: (
    en: 'Switch to light mode',
    ru: 'Включить светлую тему',
  ),
  KolkhozText.appsettingsSwitchToDarkMode: (
    en: 'Switch to dark mode',
    ru: 'Включить тёмную тему',
  ),
  KolkhozText.appsettingsCardBacks: (en: 'Card backs', ru: 'Рубашки карт'),
  KolkhozText.appsettingsClassic: (en: 'Classic', ru: 'Классика'),
  KolkhozText.appsettingsHarvest: (en: 'Harvest', ru: 'Урожай'),
  KolkhozText.appsettingsGranary: (en: 'Granary', ru: 'Амбар'),
  KolkhozText.appsettingsWinter: (en: 'Winter', ru: 'Зима'),
  KolkhozText.tabledisplayYou: (en: 'You', ru: 'Вы'),
  KolkhozText.tutorialdisplayBack: (en: 'Back', ru: 'Назад'),
  KolkhozText.tutorialdisplayDone: (en: 'Done', ru: 'Готово'),
  KolkhozText.tutorialdisplayNext: (en: 'Next', ru: 'Далее'),
  KolkhozText.tutorialdisplayForemanMisha: (
    en: 'FOREMAN MISHA',
    ru: 'БРИГАДИР МИША',
  ),
  KolkhozText.tutorialdisplayTip: (en: 'TIP', ru: 'СОВЕТ'),
  KolkhozText.tutorialdisplayDoneWellWorkedComrade: (
    en: 'Done. Well worked, comrade.',
    ru: 'Готово. Хорошая работа, товарищ.',
  ),
  KolkhozText.boardviewPassDevice: (
    en: 'Pass Device',
    ru: 'Передайте устройство',
  ),
  KolkhozText.boardviewSeatValue1IsUp: (
    en: 'Seat {value1} is up.',
    ru: 'Ходит место {value1}.',
  ),
  KolkhozText.boardviewReady: (en: 'Ready', ru: 'Готов'),
  KolkhozText.boardviewYourTurn: (en: 'YOUR TURN', ru: 'ВАШ ХОД'),
  KolkhozText.boardviewWait: (en: 'WAIT', ru: 'ЖДИТЕ'),
  KolkhozText.boardviewFamineYear: (en: 'Famine year', ru: 'Год неурожая'),
  KolkhozText.boardviewChooseTrump: (en: 'Choose Trump', ru: 'Выберите козырь'),
  KolkhozText.lowerbaractionsSwap: (en: 'Swap', ru: 'Обмен'),
  KolkhozText.lowerbaractionsUndo: (en: 'Undo', ru: 'Отменить'),
  KolkhozText.lowerbaractionsConfirm: (en: 'Confirm', ru: 'Подтвердить'),
  KolkhozText.lowerbaractionsFinish: (en: 'Finish', ru: 'Завершить'),
  KolkhozText.lowerbaractionsYearValue1: (
    en: 'Year {value1}',
    ru: 'Год {value1}',
  ),
  KolkhozText.phasedisplayYearValue1Phasename: (
    en: 'Year {value1} - {phaseName}',
    ru: 'Год {value1} - {phaseName}',
  ),
  KolkhozText.kolkhozappCancel: (en: 'Cancel', ru: 'Отмена'),
  KolkhozText.kolkhozappNewGame: (en: 'New game?', ru: 'Новая игра?'),
  KolkhozText.kolkhozappThisWillReplaceTheCurrentGame: (
    en: 'This will replace the current game.',
    ru: 'Текущая партия будет заменена.',
  ),
  KolkhozText.kolkhozappNewGame2: (en: 'New game', ru: 'Новая игра'),
  KolkhozText.kolkhozappMainMenu: (en: 'Main menu?', ru: 'Главное меню?'),
  KolkhozText.kolkhozappLeaveTheCurrentGameAndReturnToSetup: (
    en: 'Leave the current game and return to setup.',
    ru: 'Выйти из текущей партии и вернуться к настройке.',
  ),
  KolkhozText.kolkhozappMainMenu2: (en: 'Main menu', ru: 'Главное меню'),
  KolkhozText.kolkhozappRememberYouMustFollowSuitIfAble: (
    en: 'Remember, you must follow suit if able.',
    ru: 'Помните: если можете, нужно ходить в масть.',
  ),
  KolkhozText.kolkhozappSignedInProfileLoaded: (
    en: 'Signed in. Profile loaded.',
    ru: 'Вход выполнен. Профиль загружен.',
  ),
  KolkhozText.kolkhozappAccountCreatedCheckYourEmailToConfirmItThe: (
    en: 'Account created. Check your email to confirm it, then sign in.',
    ru: 'Аккаунт создан. Подтвердите email, затем войдите.',
  ),
  KolkhozText.kolkhozappAccountCreated: (
    en: 'Account created.',
    ru: 'Аккаунт создан.',
  ),
  KolkhozText.kolkhozappSignedOut: (en: 'Signed out.', ru: 'Вы вышли.'),
  KolkhozText.kolkhozappPasswordResetEmailSent: (
    en: 'Password reset email sent.',
    ru: 'Письмо для сброса пароля отправлено.',
  ),
  KolkhozText.kolkhozappSyncingProfile: (
    en: 'Syncing profile...',
    ru: 'Синхронизация профиля...',
  ),
  KolkhozText.kolkhozappProfileSaved: (
    en: 'Profile saved.',
    ru: 'Профиль сохранён.',
  ),
  KolkhozText.kolkhozappProfileLoaded: (
    en: 'Profile loaded.',
    ru: 'Профиль загружен.',
  ),
  KolkhozText.kolkhozappAccountRequestFailed: (
    en: 'Account request failed.',
    ru: 'Запрос аккаунта не удался.',
  ),
  KolkhozText.kolkhozappProfileSyncFailed: (
    en: 'Profile sync failed.',
    ru: 'Синхронизация профиля не удалась.',
  ),
  KolkhozText.kolkhozappSignInBeforeJoiningOnlinePlay: (
    en: 'Sign in before joining online play.',
    ru: 'Войдите в аккаунт перед онлайн-игрой.',
  ),
  KolkhozText.kolkhozappOnlineSignInExpiredSignInAgain: (
    en: 'Online sign-in expired. Sign in again.',
    ru: 'Онлайн-вход истёк. Войдите снова.',
  ),
  KolkhozText.kolkhozappCouldNotVerifyOnlineAccountTryAgain: (
    en: 'Could not verify your online account. Try again.',
    ru: 'Не удалось проверить онлайн-аккаунт. Повторите попытку.',
  ),
  KolkhozText.kolkhozappCloudAccountUnavailable: (
    en: 'Cloud account unavailable',
    ru: 'Облачный аккаунт недоступен',
  ),
  KolkhozText.kolkhozappConnectingAccount: (
    en: 'Connecting account...',
    ru: 'Подключение аккаунта...',
  ),
  KolkhozText.kolkhozappSignedInEmail: (
    en: 'Signed in: {email}',
    ru: 'Вход: {email}',
  ),
  KolkhozText.kolkhozappSignedIn: (en: 'Signed in', ru: 'Вход выполнен'),
  KolkhozText.kolkhozappSignedOut2: (en: 'Signed out', ru: 'Вы не вошли'),
  KolkhozText.kolkhozappGameBy: (en: 'GAME BY', ru: 'АВТОР ИГРЫ'),
  KolkhozText.kolkhozappWilliamTheisen: (
    en: 'WILLIAM THEISEN',
    ru: 'УИЛЬЯМ ТАЙСОН',
  ),
  KolkhozText.kolkhozappProfile: (en: 'Profile', ru: 'Профиль'),
  KolkhozText.kolkhozappSettings: (en: 'SETTINGS', ru: 'НАСТРОЙКИ'),
  KolkhozText.kolkhozappProgress: (en: 'PROGRESS', ru: 'ПРОГРЕСС'),
  KolkhozText.kolkhozappCouldNotReachTheOnlineServerTryAgainInAMom: (
    en: 'Could not reach the online server. Try again in a moment.',
    ru: 'Не удалось подключиться к серверу. Повторите попытку чуть позже.',
  ),
  KolkhozText.kolkhozappOnlineRequestFailedTryAgain: (
    en: 'Online request failed. Try again.',
    ru: 'Онлайн-запрос не удался. Повторите попытку.',
  ),
  KolkhozText.kolkhozappDemoMode2YearKolkhozWithEasyAi: (
    en: 'Demo mode: 2-year Kolkhoz with easy AI.',
    ru: 'Демо-режим: Колхоз на 2 года с лёгким ИИ.',
  ),
  KolkhozText.kolkhozappWorking: (en: 'Working...', ru: 'Идёт...'),
  KolkhozText.kolkhozappStartDemo: (en: 'Start Demo', ru: 'Начать демо'),
  KolkhozText.kolkhozappStartOnlineGame: (
    en: 'Start Online Game',
    ru: 'Начать онлайн',
  ),
  KolkhozText.kolkhozappStartOfflineGame: (
    en: 'Start Offline Game',
    ru: 'Начать офлайн',
  ),
  KolkhozText.kolkhozappContinueToLobby: (
    en: 'Add Players',
    ru: 'Перейти в лобби',
  ),
  KolkhozText.kolkhozappBackToSetup: (
    en: 'Back to Setup',
    ru: 'Назад к настройке',
  ),
  KolkhozText.kolkhozappSaveFavorite: (
    en: 'Save Favorite',
    ru: 'Сохранить любимую',
  ),
  KolkhozText.kolkhozappUseFavorite: (en: 'Use Favorite', ru: 'Взять любимую'),
  KolkhozText.kolkhozappFavoriteSaved: (
    en: 'Favorite setup saved',
    ru: 'Любимая настройка сохранена',
  ),
  KolkhozText.kolkhozappRanked: (en: 'Ranked', ru: 'Рейтинг'),
  KolkhozText.kolkhozappLocked: (en: 'Private', ru: 'Частная'),
  KolkhozText.kolkhozappBrowser: (en: 'Public', ru: 'Публичная'),
  KolkhozText.kolkhozappAccess: (en: 'VISIBILITY', ru: 'ВИДИМОСТЬ'),
  KolkhozText.kolkhozappComrades: (en: 'Comrades', ru: 'Товарищи'),
  KolkhozText.kolkhozappYourComradeCode: (
    en: 'YOUR COMRADE CODE',
    ru: 'ВАШ КОД ТОВАРИЩА',
  ),
  KolkhozText.kolkhozappComradeCode: (en: 'COMRADE CODE', ru: 'КОД ТОВАРИЩА'),
  KolkhozText.kolkhozappAddComrade: (en: 'Add Comrade', ru: 'Добавить'),
  KolkhozText.kolkhozappRemove: (en: 'Remove', ru: 'Убрать'),
  KolkhozText.kolkhozappNoComrades: (
    en: 'No comrades yet',
    ru: 'Товарищей пока нет',
  ),
  KolkhozText.kolkhozappComradeAdded: (
    en: 'Comrade added',
    ru: 'Товарищ добавлен',
  ),
  KolkhozText.kolkhozappComradeRequestSent: (
    en: 'Comrade request sent',
    ru: 'Запрос отправлен',
  ),
  KolkhozText.kolkhozappComrade: (en: 'Comrade', ru: 'Товарищ'),
  KolkhozText.kolkhozappNotComrade: (en: 'Not a comrade', ru: 'Не товарищ'),
  KolkhozText.kolkhozappPending: (en: 'Pending', ru: 'Ожидает'),
  KolkhozText.kolkhozappIncomingRequests: (
    en: 'Incoming Requests',
    ru: 'Входящие запросы',
  ),
  KolkhozText.kolkhozappOutgoingRequests: (
    en: 'Sent Requests',
    ru: 'Отправленные запросы',
  ),
  KolkhozText.kolkhozappNoComradeRequests: (
    en: 'No comrade requests',
    ru: 'Нет запросов',
  ),
  KolkhozText.kolkhozappAccept: (en: 'Accept', ru: 'Принять'),
  KolkhozText.kolkhozappDecline: (en: 'Decline', ru: 'Отклонить'),
  KolkhozText.kolkhozappComradeRequestAccepted: (
    en: 'Comrade request accepted',
    ru: 'Запрос принят',
  ),
  KolkhozText.kolkhozappComradeRequestDeclined: (
    en: 'Comrade request declined',
    ru: 'Запрос отклонён',
  ),
  KolkhozText.kolkhozappComradeRemoved: (
    en: 'Comrade removed',
    ru: 'Товарищ убран',
  ),
  KolkhozText.kolkhozappGameInvite: (
    en: 'Game Invite',
    ru: 'Приглашение в игру',
  ),
  KolkhozText.kolkhozappValue1InvitedYouToAGame: (
    en: '{value1} invited you to a game.',
    ru: '{value1} приглашает вас в игру.',
  ),
  KolkhozText.kolkhozappOfflineStatus: (en: 'Offline', ru: 'Не в сети'),
  KolkhozText.kolkhozappInGame: (en: 'In game', ru: 'В игре'),
  KolkhozText.kolkhozappInLobby: (en: 'In lobby', ru: 'В лобби'),
  KolkhozText.kolkhozappCasual: (en: 'Casual', ru: 'Без рейтинга'),
  KolkhozText.kolkhozappGameType: (en: 'TYPE', ru: 'ТИП'),
  KolkhozText.kolkhozappPValue1: (en: 'P{value1}', ru: 'И{value1}'),
  KolkhozText.kolkhozappHotseat: (en: 'Hotseat', ru: 'За столом'),
  KolkhozText.kolkhozappOnline: (en: 'Online', ru: 'Онлайн'),
  KolkhozText.kolkhozappDecktypeCardsMaxyearsYears: (
    en: '{deckType} CARDS / {maxYears} YEARS',
    ru: '{deckType} КАРТ / {maxYears} ГОДА',
  ),
  KolkhozText.kolkhozappHowToPlay: (en: 'HOW TO PLAY', ru: 'КАК ИГРАТЬ'),
  KolkhozText.kolkhozappTutorial: (en: 'Tutorial', ru: 'Обучение'),
  KolkhozText.kolkhozappProfile2: (en: 'PROFILE', ru: 'ПРОФИЛЬ'),
  KolkhozText.kolkhozappDisplayName: (en: 'DISPLAY NAME', ru: 'ИМЯ ИГРОКА'),
  KolkhozText.kolkhozappPortrait: (en: 'PORTRAIT', ru: 'ПОРТРЕТ'),
  KolkhozText.kolkhozappPasswordsDoNotMatch: (
    en: 'Passwords do not match.',
    ru: 'Пароли не совпадают.',
  ),
  KolkhozText.kolkhozappCloudProfilesAreNotConfiguredForThisBuild: (
    en: 'Cloud profiles are not configured for this build.',
    ru: 'Облачные профили не настроены для этой сборки.',
  ),
  KolkhozText.kolkhozappCloudProfilesAreStarting: (
    en: 'Cloud profiles are starting.',
    ru: 'Облачные профили запускаются.',
  ),
  KolkhozText.kolkhozappSignedInAsValue1: (
    en: 'Signed in as {value1}',
    ru: 'Вход: {value2}',
  ),
  KolkhozText.kolkhozappSignInToSyncProfileAndOnlineSeats: (
    en: 'Sign in to sync profile and online seats.',
    ru: 'Войдите, чтобы синхронизировать профиль и места.',
  ),
  KolkhozText.kolkhozappAccount: (en: 'ACCOUNT', ru: 'АККАУНТ'),
  KolkhozText.kolkhozappEmail: (en: 'EMAIL', ru: 'EMAIL'),
  KolkhozText.kolkhozappPassword: (en: 'PASSWORD', ru: 'ПАРОЛЬ'),
  KolkhozText.kolkhozappConfirmPassword: (
    en: 'CONFIRM PASSWORD',
    ru: 'ПОВТОРИТЕ ПАРОЛЬ',
  ),
  KolkhozText.kolkhozappSignIn: (en: 'Sign In', ru: 'Войти'),
  KolkhozText.kolkhozappReset: (en: 'Reset', ru: 'Сбросить'),
  KolkhozText.kolkhozappCreate: (en: 'Create', ru: 'Создать'),
  KolkhozText.kolkhozappSignOut: (en: 'Sign Out', ru: 'Выйти'),
  KolkhozText.kolkhozappOffline: (en: 'OFFLINE', ru: 'ОФЛАЙН'),
  KolkhozText.kolkhozappGames: (en: 'games', ru: 'игры'),
  KolkhozText.kolkhozappOffWins: (en: 'OFF WINS', ru: 'ОФЛ ПОБ'),
  KolkhozText.kolkhozappWins: (en: 'wins', ru: 'победы'),
  KolkhozText.kolkhozappOnline2: (en: 'ONLINE', ru: 'ОНЛАЙН'),
  KolkhozText.kolkhozappOnWins: (en: 'ON WINS', ru: 'ОНЛ ПОБ'),
  KolkhozText.kolkhozappCasualRating: (
    en: 'CASUAL RATING',
    ru: 'КАЗУАЛ РЕЙТИНГ',
  ),
  KolkhozText.kolkhozappRankedRating: (
    en: 'RANKED RATING',
    ru: 'РЕЙТИНГОВЫЙ РЕЙТИНГ',
  ),
  KolkhozText.kolkhozappRating: (en: 'RATING', ru: 'РЕЙТИНГ'),
  KolkhozText.kolkhozappCurrent: (en: 'current', ru: 'текущий'),
  KolkhozText.kolkhozappWins2: (en: 'WINS', ru: 'ПОБЕДЫ'),
  KolkhozText.kolkhozappTotal: (en: 'total', ru: 'всего'),
  KolkhozText.kolkhozappLosses: (en: 'LOSSES', ru: 'ПОРАЖЕНИЯ'),
  KolkhozText.kolkhozappStats: (en: 'STATS', ru: 'СТАТИСТИКА'),
  KolkhozText.kolkhozappNoOpenGames: (
    en: 'No open games',
    ru: 'Нет открытых игр',
  ),
  KolkhozText.kolkhozappValue1Open: (
    en: '{value1} open',
    ru: 'Открыто: {value1}',
  ),
  KolkhozText.kolkhozappValue1CitizensOnline: (
    en: '{value1} Citizens Online',
    ru: 'Граждан онлайн: {value1}',
  ),
  KolkhozText.kolkhozappRefreshInValue1s: (
    en: 'Refresh in {value1}s',
    ru: 'Обновление через {value1}с',
  ),
  KolkhozText.kolkhozappJoinedValue1: (
    en: 'Joined {value1}',
    ru: 'Вошли {value1}',
  ),
  KolkhozText.kolkhozappSentNorthOnlinePlayIsLockedForThisAccount: (
    en: 'Sent north: online play is locked for this account.',
    ru: 'Сослан на север: онлайн временно закрыт для аккаунта.',
  ),
  KolkhozText.kolkhozappTheOnlineServerRejectedTheRequest: (
    en: 'The online server rejected the request.',
    ru: 'Сервер отклонил запрос.',
  ),
  KolkhozText.kolkhozappOnlinePlay: (en: 'ONLINE PLAY', ru: 'ОНЛАЙН ИГРА'),
  KolkhozText.kolkhozappJoinAnOpenGameOrEnterAnInviteCode: (
    en: 'Join an open game or enter an invite code.',
    ru: 'Войдите в открытую игру или по коду.',
  ),
  KolkhozText.kolkhozappInviteCode: (en: 'INVITE CODE', ru: 'КОД ПРИГЛАШЕНИЯ'),
  KolkhozText.kolkhozappYourInviteCode: (en: 'YOUR INVITE CODE', ru: 'ВАШ КОД'),
  KolkhozText.kolkhozappWaitingForPlayers: (
    en: 'Waiting for players',
    ru: 'Ожидание игроков',
  ),
  KolkhozText.kolkhozappGameStartsInValue1s: (
    en: 'Game starts in {value1}s',
    ru: 'Игра начнётся через {value1} с',
  ),
  KolkhozText.kolkhozappSearchingForPlayer: (
    en: 'Searching for Player',
    ru: 'Поиск игрока',
  ),
  KolkhozText.kolkhozappCopyCode: (en: 'Copy Code', ru: 'Копировать код'),
  KolkhozText.kolkhozappCopyResult: (en: 'Copy Result', ru: 'Копировать итог'),
  KolkhozText.kolkhozappCopied: (en: 'Copied', ru: 'Скопировано'),
  KolkhozText.kolkhozappJoinGame: (en: 'Join Game', ru: 'Войти и играть'),
  KolkhozText.kolkhozappAssignGame: (en: 'Assign Game', ru: 'Назначить игру'),
  KolkhozText.kolkhozappKick: (en: 'Kick', ru: 'Исключить'),
  KolkhozText.kolkhozappOpenGames: (en: 'OPEN GAMES', ru: 'ОТКРЫТЫЕ ИГРЫ'),
  KolkhozText.kolkhozappRefresh: (en: 'Refresh', ru: 'Обновить'),
  KolkhozText.kolkhozappOpenOpenseats: (
    en: 'Open {openSeats}',
    ru: 'Открыто {openSeats}',
  ),
  KolkhozText.kolkhozappHost: (en: 'HOST', ru: 'ХОЗЯИН'),
  KolkhozText.kolkhozappSeats: (en: 'SEATS', ru: 'МЕСТА'),
  KolkhozText.kolkhozappTurn: (en: 'TURN', ru: 'ХОД'),
  KolkhozText.kolkhozappMoves: (en: 'MOVES', ru: 'ХОДЫ'),
  KolkhozText.kolkhozappWaiting: (en: 'WAITING', ru: 'ОЖИДАНИЕ'),
  KolkhozText.kolkhozappOpen: (en: 'OPEN', ru: 'СВОБОДНО'),
  KolkhozText.kolkhozappAverageRating: (en: 'AVG RATING', ru: 'СР РЕЙТИНГ'),
  KolkhozText.kolkhozappPlayer: (en: 'PLAYER', ru: 'ИГРОК'),
  KolkhozText.kolkhozappScore: (en: 'SCORE', ru: 'ОЧКИ'),
  KolkhozText.kolkhozappMedals: (en: 'MEDALS', ru: 'МЕДАЛИ'),
  KolkhozText.kolkhozappHand: (en: 'HAND', ru: 'РУКА'),
  KolkhozText.kolkhozappCellar: (en: 'CELLAR', ru: 'ПОДВАЛ'),
  KolkhozText.kolkhozappPlot: (en: 'PLOT', ru: 'УЧАСТОК'),
  KolkhozText.kolkhozappController: (en: 'CONTROL', ru: 'УПРАВЛЕНИЕ'),
  KolkhozText.kolkhozappBrigadeLeader: (en: 'BRIGADE LEADER', ru: 'БРИГАДИР'),
  KolkhozText.kolkhozappCurrentTurn: (en: 'CURRENT TURN', ru: 'ТЕКУЩИЙ ХОД'),
  KolkhozText.kolkhozappAny: (en: 'Any', ru: 'Любое'),
  KolkhozText.kolkhozappHuman: (en: 'Human', ru: 'Игрок'),
  KolkhozText.kolkhozappEasy: (en: 'Easy', ru: 'Легко'),
  KolkhozText.kolkhozappMedium: (en: 'Medium', ru: 'Средне'),
  KolkhozText.kolkhozappHard: (en: 'Hard', ru: 'Сложно'),
  KolkhozText.plotdisplayOtherStoresAboveActivePlayerSCellarBelow: (
    en: 'Other stores above, active player\'s cellar below.',
    ru: 'Участки других сверху, подвал активного игрока снизу.',
  ),
  KolkhozText.plotdisplayAllJobsComplete: (
    en: 'All jobs complete.',
    ru: 'Все работы выполнены.',
  ),
  KolkhozText.plotdisplayAuditComplete: (
    en: 'Audit complete.',
    ru: 'Проверка завершена.',
  ),
  KolkhozText.boardOptionspanelInstant: (en: 'Instant', ru: 'Мигом'),
  KolkhozText.boardOptionspanelFast: (en: 'Fast', ru: 'Быстро'),
  KolkhozText.boardOptionspanelNormal: (en: 'Normal', ru: 'Норма'),
  KolkhozText.boardOptionspanelSlow: (en: 'Slow', ru: 'Медленно'),
  KolkhozText.boardOptionspanelSession: (en: 'Session', ru: 'Партия'),
  KolkhozText.boardOptionspanelAssist: (en: 'Assist', ru: 'Помощь'),
  KolkhozText.boardOptionspanelDisplay: (en: 'Display', ru: 'Вид'),
  KolkhozText.boardOptionspanelRules: (en: 'Rules', ru: 'Правила'),
  KolkhozText.boardOptionspanelMenu: (en: 'Menu', ru: 'Меню'),
  KolkhozText.boardOptionspanelGameControls: (
    en: 'Game controls',
    ru: 'Управление игрой',
  ),
  KolkhozText.boardOptionspanelHowToPlay: (en: 'How to play', ru: 'Как играть'),
  KolkhozText.boardOptionspanelSafeguards: (en: 'Safeguards', ru: 'Защита'),
  KolkhozText.boardOptionspanelConfirmNewGame: (
    en: 'Confirm new game',
    ru: 'Подтверждать новую игру',
  ),
  KolkhozText.boardOptionspanelAskBeforeReplacingTheCurrentGame: (
    en: 'Ask before replacing the current game.',
    ru: 'Спросить перед заменой текущей партии.',
  ),
  KolkhozText.boardOptionspanelConfirmMainMenu: (
    en: 'Confirm main menu',
    ru: 'Подтверждать выход',
  ),
  KolkhozText.boardOptionspanelAskBeforeLeavingTheCurrentGame: (
    en: 'Ask before leaving the current game.',
    ru: 'Спросить перед выходом из текущей партии.',
  ),
  KolkhozText.boardOptionspanelMoveHelp: (en: 'Move help', ru: 'Помощь хода'),
  KolkhozText.boardOptionspanelInvalidTapHints: (
    en: 'Invalid-tap hints',
    ru: 'Подсказки ошибок',
  ),
  KolkhozText.boardOptionspanelShowTheForemanReminderWhenYouTapAnIllegalC: (
    en: 'Show the Foreman reminder when you tap an illegal card.',
    ru: 'Показывать напоминание бригадира при неверной карте.',
  ),
  KolkhozText.boardOptionspanelAnimationSpeed: (
    en: 'Animation speed',
    ru: 'Скорость анимации',
  ),
  KolkhozText.boardPlotpanelRequisition: (en: 'Requisition', ru: 'Реквизиция'),
  KolkhozText.boardPlotpanelPrivatePlot: (
    en: 'Private plot',
    ru: 'Личный участок',
  ),
  KolkhozText.boardPlotpanelGameOver: (en: 'Game Over', ru: 'Игра окончена'),
  KolkhozText.boardPlotpanelWinnerWinnernameWinnerscore: (
    en: 'Winner: {winnerName} - {winnerScore}',
    ru: 'Победитель: {winnerName} - {winnerScore}',
  ),
  KolkhozText.boardHandtrayUndo: (en: 'Undo', ru: 'Назад'),
  KolkhozText.boardHandtrayPlay: (en: 'Play', ru: 'Ход'),
  KolkhozText.handConsoleYourTurnToPlay: (
    en: 'Your turn to play',
    ru: 'Ваш ход',
  ),
  KolkhozText.handConsoleChooseSwap: (
    en: 'Choose a swap',
    ru: 'Выберите обмен',
  ),
  KolkhozText.handConsoleAssignTrick: (
    en: 'Assign the trick',
    ru: 'Распределите взятку',
  ),
  KolkhozText.handConsoleReviewRequisition: (
    en: 'Review requisition',
    ru: 'Проверьте реквизицию',
  ),
  KolkhozText.handConsoleWaitingForValue1: (
    en: 'Waiting for {value1}',
    ru: 'Ждём: {value1}',
  ),
  KolkhozText.handConsoleWaitingForValue1ToPlay: (
    en: 'Waiting for {value1} to play',
    ru: 'Ждём хода: {value1}',
  ),
  KolkhozText.handConsoleWaitingForValue1ToSwap: (
    en: 'Waiting for {value1} to swap',
    ru: 'Ждём обмена: {value1}',
  ),
  KolkhozText.handConsoleWaitingForValue1ToAssign: (
    en: 'Waiting for {value1} to assign',
    ru: 'Ждём работ: {value1}',
  ),
  KolkhozText.handConsoleContinue: (en: 'Continue', ru: 'Далее'),
  KolkhozText.boardJobspanelDone: (en: 'DONE', ru: 'ГОТОВО'),
  KolkhozText.boardJobspanelTapToAssign: (en: 'TAP TO ASSIGN', ru: 'НАЗНАЧИТЬ'),
  KolkhozText.boardBoardrailBoard: (en: 'Board', ru: 'Стол'),
  KolkhozText.boardBoardrailJobs: (en: 'Jobs', ru: 'Работы'),
  KolkhozText.boardBoardrailNorth: (en: 'North', ru: 'Север'),
  KolkhozText.boardBoardrailCellar: (en: 'Cellar', ru: 'Подвал'),
  KolkhozText.boardBoardrailLang: (en: 'Lang', ru: 'Язык'),
  KolkhozText.boardBoardrailBrigade: (en: 'Brigade', ru: 'Бригада'),
  KolkhozText.boardBoardrailTheNorth: (en: 'The North', ru: 'Север'),
  KolkhozText.ruleSummary1Title: (en: 'Objective', ru: 'Цель'),
  KolkhozText.ruleSummary1Body: (
    en: 'Complete collective farm jobs while protecting your private plot. Highest score wins!',
    ru: 'Выполняйте работы колхоза, защищая свой участок. Побеждает наибольший счёт!',
  ),
  KolkhozText.ruleSummary2Title: (en: 'Gameplay', ru: 'Игра'),
  KolkhozText.ruleSummary2Body: (
    en: 'Play cards to tricks - must follow lead suit if able.',
    ru: 'Играйте карты во взятки - следуйте масти если возможно.',
  ),
  KolkhozText.ruleSummary3Title: (en: 'Jobs', ru: 'Работы'),
  KolkhozText.ruleSummary3Body: (
    en: 'Jobs need 40 work hours to complete.',
    ru: 'Работы требуют 40 часов для завершения.',
  ),
  KolkhozText.ruleSummary4Title: (en: 'Trump Face Cards', ru: 'Козырные карты'),
  KolkhozText.ruleSummary4Body: (
    en: 'Jack, Queen, and King have special powers in nomenclature games.',
    ru: 'Валет, Дама и Король имеют особые силы в игре с номенклатурой.',
  ),
  KolkhozText.ruleSummary5Title: (en: 'Scoring', ru: 'Подсчёт очков'),
  KolkhozText.ruleSummary5Body: (
    en: 'Cards in your plot equal your score. Highest score wins.',
    ru: 'Карты на вашем участке дают очки. Побеждает тот, у кого больше.',
  ),
  KolkhozText.ruleSummary6Title: (en: 'Work', ru: 'Работы'),
  KolkhozText.ruleSummary6Body: (
    en: 'Win tricks, then assign captured cards to matching jobs.',
    ru: 'Выигрывайте взятки и назначайте карты на подходящие работы.',
  ),
  KolkhozText.ruleSummary7Title: (en: 'Protect', ru: 'Защита'),
  KolkhozText.ruleSummary7Body: (
    en: 'Keep plot cards safe from failed-job requisition.',
    ru: 'Берегите карты участка от реквизиции за проваленные работы.',
  ),
  KolkhozText.ruleSummary8Title: (en: 'Trump faces', ru: 'Козырные карты'),
  KolkhozText.ruleSummary8Body: (
    en: 'Jack goes north, Queen exposes, King doubles exile.',
    ru: 'Валет уходит на Север, Дама раскрывает, Король удваивает ссылку.',
  ),
  KolkhozText.tutorialStep1Title: (
    en: 'Welcome to the collective',
    ru: 'Добро пожаловать в колхоз',
  ),
  KolkhozText.tutorialStep1Body: (
    en: 'This is a real game, comrade — play while we talk. Your goal: end the Five-Year Plan with the most points hidden in your cellar.',
    ru: 'Это настоящая игра, товарищ — играйте, пока мы говорим. Цель: закончить пятилетку с самым богатым подвалом.',
  ),
  KolkhozText.tutorialStep1Tip: (
    en: 'High hidden cards are your bank. Losing one to the North can swing the final score.',
    ru: 'Старшие скрытые карты — ваш запас. Потеря одной на Севере может решить итоговый счёт.',
  ),
  KolkhozText.tutorialStep1Callout: (
    en: 'The buttons below turn my lessons. The board stays yours.',
    ru: 'Кнопки листают уроки. Стол остаётся вашим.',
  ),
  KolkhozText.tutorialStep2Title: (
    en: 'Read the work board',
    ru: 'Осмотрите доску работ',
  ),
  KolkhozText.tutorialStep2Body: (
    en: 'Four jobs each year, one per crop. The card by each job is its reward; the counter is work hours — 40 completes the job.',
    ru: 'Каждый год четыре работы, по одной на культуру. Карта у работы — награда; счётчик — часы: 40 закрывают работу.',
  ),
  KolkhozText.tutorialStep2Tip: (
    en: 'Failed jobs summon requisition at year\'s end. Remember which crops look doomed.',
    ru: 'Проваленные работы зовут реквизицию в конце года. Запоминайте обречённые культуры.',
  ),
  KolkhozText.tutorialStep2Callout: (
    en: 'Find the four job counters along the top of the table.',
    ru: 'Найдите четыре счётчика работ наверху стола.',
  ),
  KolkhozText.tutorialStep3Title: (
    en: 'The trump crop',
    ru: 'Козырная культура',
  ),
  KolkhozText.tutorialStep3Body: (
    en: 'In planning, one crop is declared the State\'s main task — trump. Trump cards beat the led crop in any trick.',
    ru: 'В планировании одну культуру объявляют главной задачей — козырем. Козырь бьёт ведущую масть в любой взятке.',
  ),
  KolkhozText.tutorialStep3Tip: (
    en: 'Pick trump for the hand you expect to play, not only for the biggest card you see.',
    ru: 'Выбирайте козырь под руку, которую хотите разыграть, а не только под самую крупную карту.',
  ),
  KolkhozText.tutorialStep3Callout: (
    en: 'Waiting for trump to be declared…',
    ru: 'Ждём объявления козыря…',
  ),
  KolkhozText.tutorialStep4Title: (en: 'Play a card', ru: 'Сыграйте карту'),
  KolkhozText.tutorialStep4Body: (
    en: 'Follow the led crop if you can — legal cards glow. Out of that crop? Play anything, even trump.',
    ru: 'Ходите в масть, если можете — разрешённые карты подсвечены. Нет масти? Кладите что угодно, хоть козырь.',
  ),
  KolkhozText.tutorialStep4Tip: (
    en: 'Ducking a trick is allowed — and often wise. Winners attract attention.',
    ru: 'Уступить взятку можно — и часто мудро. Победители привлекают внимание.',
  ),
  KolkhozText.tutorialStep4Callout: (
    en: 'Play a card from your hand when your turn comes.',
    ru: 'Сыграйте карту с руки, когда придёт ваш ход.',
  ),
  KolkhozText.tutorialStep5Title: (en: 'Taking the trick', ru: 'Взятие взятки'),
  KolkhozText.tutorialStep5Body: (
    en: 'Highest card of the led crop wins — unless trump lands; then the highest trump. The winner takes a medal and becomes brigade leader.',
    ru: 'Взятку берёт старшая карта ведущей масти — если не лёг козырь: тогда старший козырь. Победитель берёт медаль и становится бригадиром.',
  ),
  KolkhozText.tutorialStep5Tip: (
    en: 'Medals break ties at the end — but every win paints a target on your cellar.',
    ru: 'Медали решают ничьи в конце — но каждая победа рисует мишень на подвале.',
  ),
  KolkhozText.tutorialStep5Callout: (
    en: 'Watch who takes this trick.',
    ru: 'Смотрите, кто возьмёт эту взятку.',
  ),
  KolkhozText.tutorialStep6Title: (
    en: 'Assign the labor',
    ru: 'Назначьте работу',
  ),
  KolkhozText.tutorialStep6Body: (
    en: 'The brigade leader sends the trick\'s cards to jobs — only crops present in the trick are legal targets. A card\'s rank is its hours.',
    ru: 'Бригадир отправляет карты взятки на работы — законны только культуры из взятки. Ранг карты — её часы.',
  ),
  KolkhozText.tutorialStep6Tip: (
    en: 'Assign work to protect the crops that match your best cellar cards.',
    ru: 'Назначайте работу, защищая культуры своих лучших карт подвала.',
  ),
  KolkhozText.tutorialStep6Callout: (
    en: 'When you win a trick, tap its cards onto jobs.',
    ru: 'Выиграв взятку, распределите её карты по работам.',
  ),
  KolkhozText.tutorialStep7Title: (en: 'Meet the quota', ru: 'Выполните норму'),
  KolkhozText.tutorialStep7Body: (
    en: 'A job that reaches 40 hours is complete: its reward drops into the closer\'s cellar, and that crop is safe from requisition this year.',
    ru: 'Работа с 40 часами закрыта: награда падает в подвал закрывшего, и эта культура в этом году не вызовет реквизицию.',
  ),
  KolkhozText.tutorialStep7Tip: (
    en: 'A finished job pays you and protects you. Two birds, one quota.',
    ru: 'Закрытая работа и платит, и защищает. Две птицы — одна норма.',
  ),
  KolkhozText.tutorialStep7Callout: (
    en: 'Push a job to 40 hours to claim its reward.',
    ru: 'Доведите работу до 40 часов и заберите награду.',
  ),
  KolkhozText.tutorialStep8Title: (
    en: 'The leftover card',
    ru: 'Последняя карта',
  ),
  KolkhozText.tutorialStep8Body: (
    en: 'Only four tricks are played. Your fifth card slips face-down into your cellar at year\'s end — its rank becomes points.',
    ru: 'Взяток только четыре. Пятая карта в конце года уходит в подвал рубашкой вверх — её ранг станет очками.',
  ),
  KolkhozText.tutorialStep8Tip: (
    en: 'Steer the year so your best card is the one that survives.',
    ru: 'Ведите год так, чтобы уцелела лучшая карта.',
  ),
  KolkhozText.tutorialStep8Callout: (
    en: 'Your unplayed card banks itself when the year ends.',
    ru: 'Несыгранная карта спрячется сама в конце года.',
  ),
  KolkhozText.tutorialStep9Title: (
    en: 'This is requisition',
    ru: 'Это реквизиция',
  ),
  KolkhozText.tutorialStep9Body: (
    en: 'For every failed crop, trick winners reveal their highest matching cellar card — and it is exiled North, gone for good.',
    ru: 'За каждую проваленную культуру бравшие взятки открывают старшую карту этой масти из подвала — и она уходит на Север навсегда.',
  ),
  KolkhozText.tutorialStep9Tip: (
    en: 'Never won a trick? Nothing to confess. Cowardice has its rewards.',
    ru: 'Не брали взяток? Нечего предъявить. У трусости свои награды.',
  ),
  KolkhozText.tutorialStep9Callout: (
    en: 'Read the requisition report carefully.',
    ru: 'Внимательно изучите отчёт о реквизиции.',
  ),
  KolkhozText.tutorialStep10Title: (
    en: 'The yearly swap',
    ru: 'Ежегодный обмен',
  ),
  KolkhozText.tutorialStep10Body: (
    en: 'From year two, planning ends with a swap: trade one hand card for one cellar card — or pass. Once per year.',
    ru: 'Со второго года после планирования — обмен: одна карта руки на одну карту подвала, или пас. Раз в год.',
  ),
  KolkhozText.tutorialStep10Tip: (
    en: 'Bury high cards while they are safe; pull out crops that look doomed.',
    ru: 'Прячьте старшие карты, пока безопасно; вытаскивайте обречённые культуры.',
  ),
  KolkhozText.tutorialStep10Callout: (
    en: 'Try a swap when the new year begins.',
    ru: 'Попробуйте обмен в начале нового года.',
  ),
  KolkhozText.tutorialStep11Title: (
    en: 'Beware the Wrecker',
    ru: 'Берегитесь Вредителя',
  ),
  KolkhozText.tutorialStep11Body: (
    en: 'One joker hides among the workers: he follows any suit and brings 14 hours — but any job holding him fails inspection anyway.',
    ru: 'Среди рабочих прячется джокер: ходит под любую масть, даёт 14 часов — но работа с ним всё равно проваливает проверку.',
  ),
  KolkhozText.tutorialStep11Tip: (
    en: 'Win him boldly, bury him bitterly — or make him someone else\'s problem.',
    ru: 'Берите его смело, прячьте с горечью — или сделайте чужой проблемой.',
  ),
  KolkhozText.tutorialStep11Callout: (
    en: 'He plays by Kolkhoz rules — watch for the wild card.',
    ru: 'Он в правилах «Колхоза» — следите за джокером.',
  ),
  KolkhozText.tutorialStep12Title: (
    en: 'Year five is famine',
    ru: 'Пятый год — голод',
  ),
  KolkhozText.tutorialStep12Body: (
    en: 'The last year is lean: four cards, three tricks, no trump at all. Short, and usually decisive.',
    ru: 'Последний год скуден: четыре карты, три взятки и никакого козыря. Коротко — и обычно решающе.',
  ),
  KolkhozText.tutorialStep12Tip: (
    en: 'Save flexible high cards for famine; without trump a bad lead is hard to escape.',
    ru: 'Приберегите гибкие старшие карты на голод; без козыря плохой ход не исправить.',
  ),
  KolkhozText.tutorialStep12Callout: (
    en: 'Waiting for the famine year…',
    ru: 'Ждём голодного года…',
  ),
  KolkhozText.tutorialStep13Title: (
    en: 'Highest final cellar wins',
    ru: 'Побеждает лучший подвал',
  ),
  KolkhozText.tutorialStep13Body: (
    en: 'After year five, every cellar card counts its rank. Highest total wins the Plan; medals break ties. Make me proud, comrade.',
    ru: 'После пятого года каждая карта подвала приносит свой ранг. Наибольшая сумма выигрывает пятилетку; медали решают ничьи. Не подведите, товарищ.',
  ),
  KolkhozText.tutorialStep13Tip: (
    en: 'One protected King is worth a year of caution.',
    ru: 'Один сбережённый король стоит года осторожности.',
  ),
  KolkhozText.tutorialStep13Callout: (
    en: 'Finish the Plan — Misha is watching.',
    ru: 'Закончите пятилетку — Миша следит.',
  ),
  KolkhozText.suitWheat: (en: 'Wheat', ru: 'Пшеница'),
  KolkhozText.suitSunflower: (en: 'Sunflower', ru: 'Подсолнух'),
  KolkhozText.suitPotatoes: (en: 'Potatoes', ru: 'Картофель'),
  KolkhozText.suitBeets: (en: 'Beets', ru: 'Свёкла'),
  KolkhozText.phasePlanning: (en: 'Planning', ru: 'План'),
  KolkhozText.phaseSwap: (en: 'Swap', ru: 'Обмен'),
  KolkhozText.phaseTrick: (en: 'Trick', ru: 'Взятка'),
  KolkhozText.phaseAssignment: (en: 'Assignment', ru: 'Работы'),
  KolkhozText.phaseRequisition: (en: 'Requisition', ru: 'Реквизиция'),
  KolkhozText.phaseGameOver: (en: 'Game Over', ru: 'Итог'),
  KolkhozText.languageSwitchTitle: (
    en: 'Switch to Russian',
    ru: 'Switch to English',
  ),
};

String lookupKolkhozText(
  KolkhozText key, {
  required bool russian,
  Map<String, Object?> args = const {},
}) {
  final entry = kolkhozText[key];
  if (entry == null) {
    throw StateError('Missing translation for $key');
  }
  var value = russian ? entry.ru : entry.en;
  for (final arg in args.entries) {
    value = value.replaceAll('{${arg.key}}', '${arg.value}');
  }
  return value;
}
