bind 127.0.0.1
protected-mode yes
port 16379
databases 16
dir /var/lib/redis-greenfield
dbfilename dump.rdb
appendonly yes
appendfilename appendonly.aof
appendfsync everysec
maxmemory 64mb
maxmemory-policy noeviction
maxclients 1000
save 900 1
save 300 10
save 60 10000
loglevel notice
daemonize no
