import 'package:flutter/widgets.dart';
import 'package:kolkhoz_app/l10n/app_localizations.dart';

export 'package:kolkhoz_app/l10n/app_localizations.dart';

/// Keys that still need runtime selection (tutorial content and descriptor data).
/// Ordinary UI strings use the generated [AppLocalizations] accessors directly.
enum KolkhozText {
  handConsoleContinue,
  handConsoleReviewRequisition,
  handConsoleWaitingForValue1,
  handConsoleWaitingForValue1ToAssign,
  handConsoleWaitingForValue1ToPlay,
  handConsoleWaitingForValue1ToSwap,
  kolkhozappAccept,
  kolkhozappAddComrade,
  kolkhozappCasual,
  kolkhozappComradeCode,
  kolkhozappComradeRequestAccepted,
  kolkhozappComradeRequestDeclined,
  kolkhozappRanked,
  languageSwitchTitle,
  lobbyCreateGame,
  lobbyPlayDemo,
  lowerbaractionsFinish,
  phaseAssignment,
  phaseGameOver,
  phasePlanning,
  phaseRequisition,
  phaseSwap,
  phaseTrick,
  ruleSummary1Body,
  ruleSummary1Title,
  ruleSummary2Body,
  ruleSummary2Title,
  ruleSummary3Body,
  ruleSummary3Title,
  ruleSummary4Body,
  ruleSummary4Title,
  ruleSummary5Body,
  ruleSummary5Title,
  ruleSummary6Body,
  ruleSummary6Title,
  ruleSummary7Body,
  ruleSummary7Title,
  ruleSummary8Body,
  ruleSummary8Title,
  suitBeets,
  suitPotatoes,
  suitSunflower,
  suitWheat,
  tabledisplayYou,
  tutorialStep10Body,
  tutorialStep10Callout,
  tutorialStep10Tip,
  tutorialStep10Title,
  tutorialStep11Body,
  tutorialStep11Callout,
  tutorialStep11Tip,
  tutorialStep11Title,
  tutorialStep12Body,
  tutorialStep12Callout,
  tutorialStep12Tip,
  tutorialStep12Title,
  tutorialStep13Body,
  tutorialStep13Callout,
  tutorialStep13Tip,
  tutorialStep13Title,
  tutorialStep1Body,
  tutorialStep1Callout,
  tutorialStep1Tip,
  tutorialStep1Title,
  tutorialStep2Body,
  tutorialStep2Callout,
  tutorialStep2Tip,
  tutorialStep2Title,
  tutorialStep3Body,
  tutorialStep3Callout,
  tutorialStep3Tip,
  tutorialStep3Title,
  tutorialStep4Body,
  tutorialStep4Callout,
  tutorialStep4Tip,
  tutorialStep4Title,
  tutorialStep5Body,
  tutorialStep5Callout,
  tutorialStep5Tip,
  tutorialStep5Title,
  tutorialStep6Body,
  tutorialStep6Callout,
  tutorialStep6Tip,
  tutorialStep6Title,
  tutorialStep7Body,
  tutorialStep7Callout,
  tutorialStep7Tip,
  tutorialStep7Title,
  tutorialStep8Body,
  tutorialStep8Callout,
  tutorialStep8Tip,
  tutorialStep8Title,
  tutorialStep9Body,
  tutorialStep9Callout,
  tutorialStep9Tip,
  tutorialStep9Title,
  variantAccumulationDescription,
  variantAccumulationTitle,
  variantDemoModeDescription,
  variantDemoModeTitle,
  variantFinalYearTrumpDescription,
  variantFinalYearTrumpTitle,
  variantHeroDescription,
  variantHeroTitle,
  variantHighestCardsRequisitionDescription,
  variantHighestCardsRequisitionTitle,
  variantLottoRewardsDescription,
  variantLottoRewardsTitle,
  variantMedalsDescription,
  variantMedalsTitle,
  variantMiceDescription,
  variantMiceTitle,
  variantNomenklaturaDescription,
  variantNomenklaturaTitle,
  variantNorthernStyleDescription,
  variantNorthernStyleTitle,
  variantOrdenNachalnikuDescription,
  variantOrdenNachalnikuTitle,
  variantPassCardsDescription,
  variantPassCardsTitle,
  variantSwapDescription,
  variantSwapTitle,
  variantWreckerDescription,
  variantWreckerTitle,
}

extension AppLocalizationsContext on BuildContext {
  AppLocalizations get strings => AppLocalizations.of(this);
}

String lookupKolkhozText(
  KolkhozText key, {
  required bool russian,
  Map<String, Object?> args = const {},
}) {
  final strings = lookupAppLocalizations(Locale(russian ? 'ru' : 'en'));
  return switch (key) {
    KolkhozText.handConsoleContinue => strings.handConsoleContinue,
    KolkhozText.handConsoleReviewRequisition =>
      strings.handConsoleReviewRequisition,
    KolkhozText.handConsoleWaitingForValue1 =>
      strings.handConsoleWaitingForValue1(value1: args['value1']!),
    KolkhozText.handConsoleWaitingForValue1ToAssign =>
      strings.handConsoleWaitingForValue1ToAssign(value1: args['value1']!),
    KolkhozText.handConsoleWaitingForValue1ToPlay =>
      strings.handConsoleWaitingForValue1ToPlay(value1: args['value1']!),
    KolkhozText.handConsoleWaitingForValue1ToSwap =>
      strings.handConsoleWaitingForValue1ToSwap(value1: args['value1']!),
    KolkhozText.kolkhozappAccept => strings.kolkhozappAccept,
    KolkhozText.kolkhozappAddComrade => strings.kolkhozappAddComrade,
    KolkhozText.kolkhozappCasual => strings.kolkhozappCasual,
    KolkhozText.kolkhozappComradeCode => strings.kolkhozappComradeCode,
    KolkhozText.kolkhozappComradeRequestAccepted =>
      strings.kolkhozappComradeRequestAccepted,
    KolkhozText.kolkhozappComradeRequestDeclined =>
      strings.kolkhozappComradeRequestDeclined,
    KolkhozText.kolkhozappRanked => strings.kolkhozappRanked,
    KolkhozText.languageSwitchTitle => strings.languageSwitchTitle,
    KolkhozText.lobbyCreateGame => strings.lobbyCreateGame,
    KolkhozText.lobbyPlayDemo => strings.lobbyPlayDemo,
    KolkhozText.lowerbaractionsFinish => strings.lowerbaractionsFinish,
    KolkhozText.phaseAssignment => strings.phaseAssignment,
    KolkhozText.phaseGameOver => strings.phaseGameOver,
    KolkhozText.phasePlanning => strings.phasePlanning,
    KolkhozText.phaseRequisition => strings.phaseRequisition,
    KolkhozText.phaseSwap => strings.phaseSwap,
    KolkhozText.phaseTrick => strings.phaseTrick,
    KolkhozText.ruleSummary1Body => strings.ruleSummary1Body,
    KolkhozText.ruleSummary1Title => strings.ruleSummary1Title,
    KolkhozText.ruleSummary2Body => strings.ruleSummary2Body,
    KolkhozText.ruleSummary2Title => strings.ruleSummary2Title,
    KolkhozText.ruleSummary3Body => strings.ruleSummary3Body,
    KolkhozText.ruleSummary3Title => strings.ruleSummary3Title,
    KolkhozText.ruleSummary4Body => strings.ruleSummary4Body,
    KolkhozText.ruleSummary4Title => strings.ruleSummary4Title,
    KolkhozText.ruleSummary5Body => strings.ruleSummary5Body,
    KolkhozText.ruleSummary5Title => strings.ruleSummary5Title,
    KolkhozText.ruleSummary6Body => strings.ruleSummary6Body,
    KolkhozText.ruleSummary6Title => strings.ruleSummary6Title,
    KolkhozText.ruleSummary7Body => strings.ruleSummary7Body,
    KolkhozText.ruleSummary7Title => strings.ruleSummary7Title,
    KolkhozText.ruleSummary8Body => strings.ruleSummary8Body,
    KolkhozText.ruleSummary8Title => strings.ruleSummary8Title,
    KolkhozText.suitBeets => strings.suitBeets,
    KolkhozText.suitPotatoes => strings.suitPotatoes,
    KolkhozText.suitSunflower => strings.suitSunflower,
    KolkhozText.suitWheat => strings.suitWheat,
    KolkhozText.tabledisplayYou => strings.tabledisplayYou,
    KolkhozText.tutorialStep10Body => strings.tutorialStep10Body,
    KolkhozText.tutorialStep10Callout => strings.tutorialStep10Callout,
    KolkhozText.tutorialStep10Tip => strings.tutorialStep10Tip,
    KolkhozText.tutorialStep10Title => strings.tutorialStep10Title,
    KolkhozText.tutorialStep11Body => strings.tutorialStep11Body,
    KolkhozText.tutorialStep11Callout => strings.tutorialStep11Callout,
    KolkhozText.tutorialStep11Tip => strings.tutorialStep11Tip,
    KolkhozText.tutorialStep11Title => strings.tutorialStep11Title,
    KolkhozText.tutorialStep12Body => strings.tutorialStep12Body,
    KolkhozText.tutorialStep12Callout => strings.tutorialStep12Callout,
    KolkhozText.tutorialStep12Tip => strings.tutorialStep12Tip,
    KolkhozText.tutorialStep12Title => strings.tutorialStep12Title,
    KolkhozText.tutorialStep13Body => strings.tutorialStep13Body,
    KolkhozText.tutorialStep13Callout => strings.tutorialStep13Callout,
    KolkhozText.tutorialStep13Tip => strings.tutorialStep13Tip,
    KolkhozText.tutorialStep13Title => strings.tutorialStep13Title,
    KolkhozText.tutorialStep1Body => strings.tutorialStep1Body,
    KolkhozText.tutorialStep1Callout => strings.tutorialStep1Callout,
    KolkhozText.tutorialStep1Tip => strings.tutorialStep1Tip,
    KolkhozText.tutorialStep1Title => strings.tutorialStep1Title,
    KolkhozText.tutorialStep2Body => strings.tutorialStep2Body,
    KolkhozText.tutorialStep2Callout => strings.tutorialStep2Callout,
    KolkhozText.tutorialStep2Tip => strings.tutorialStep2Tip,
    KolkhozText.tutorialStep2Title => strings.tutorialStep2Title,
    KolkhozText.tutorialStep3Body => strings.tutorialStep3Body,
    KolkhozText.tutorialStep3Callout => strings.tutorialStep3Callout,
    KolkhozText.tutorialStep3Tip => strings.tutorialStep3Tip,
    KolkhozText.tutorialStep3Title => strings.tutorialStep3Title,
    KolkhozText.tutorialStep4Body => strings.tutorialStep4Body,
    KolkhozText.tutorialStep4Callout => strings.tutorialStep4Callout,
    KolkhozText.tutorialStep4Tip => strings.tutorialStep4Tip,
    KolkhozText.tutorialStep4Title => strings.tutorialStep4Title,
    KolkhozText.tutorialStep5Body => strings.tutorialStep5Body,
    KolkhozText.tutorialStep5Callout => strings.tutorialStep5Callout,
    KolkhozText.tutorialStep5Tip => strings.tutorialStep5Tip,
    KolkhozText.tutorialStep5Title => strings.tutorialStep5Title,
    KolkhozText.tutorialStep6Body => strings.tutorialStep6Body,
    KolkhozText.tutorialStep6Callout => strings.tutorialStep6Callout,
    KolkhozText.tutorialStep6Tip => strings.tutorialStep6Tip,
    KolkhozText.tutorialStep6Title => strings.tutorialStep6Title,
    KolkhozText.tutorialStep7Body => strings.tutorialStep7Body,
    KolkhozText.tutorialStep7Callout => strings.tutorialStep7Callout,
    KolkhozText.tutorialStep7Tip => strings.tutorialStep7Tip,
    KolkhozText.tutorialStep7Title => strings.tutorialStep7Title,
    KolkhozText.tutorialStep8Body => strings.tutorialStep8Body,
    KolkhozText.tutorialStep8Callout => strings.tutorialStep8Callout,
    KolkhozText.tutorialStep8Tip => strings.tutorialStep8Tip,
    KolkhozText.tutorialStep8Title => strings.tutorialStep8Title,
    KolkhozText.tutorialStep9Body => strings.tutorialStep9Body,
    KolkhozText.tutorialStep9Callout => strings.tutorialStep9Callout,
    KolkhozText.tutorialStep9Tip => strings.tutorialStep9Tip,
    KolkhozText.tutorialStep9Title => strings.tutorialStep9Title,
    KolkhozText.variantAccumulationDescription =>
      strings.variantAccumulationDescription,
    KolkhozText.variantAccumulationTitle => strings.variantAccumulationTitle,
    KolkhozText.variantDemoModeDescription =>
      strings.variantDemoModeDescription,
    KolkhozText.variantDemoModeTitle => strings.variantDemoModeTitle,
    KolkhozText.variantFinalYearTrumpDescription =>
      strings.variantFinalYearTrumpDescription,
    KolkhozText.variantFinalYearTrumpTitle =>
      strings.variantFinalYearTrumpTitle,
    KolkhozText.variantHeroDescription => strings.variantHeroDescription,
    KolkhozText.variantHeroTitle => strings.variantHeroTitle,
    KolkhozText.variantHighestCardsRequisitionDescription =>
      strings.variantHighestCardsRequisitionDescription,
    KolkhozText.variantHighestCardsRequisitionTitle =>
      strings.variantHighestCardsRequisitionTitle,
    KolkhozText.variantLottoRewardsDescription =>
      strings.variantLottoRewardsDescription,
    KolkhozText.variantLottoRewardsTitle => strings.variantLottoRewardsTitle,
    KolkhozText.variantMedalsDescription => strings.variantMedalsDescription,
    KolkhozText.variantMedalsTitle => strings.variantMedalsTitle,
    KolkhozText.variantMiceDescription => strings.variantMiceDescription,
    KolkhozText.variantMiceTitle => strings.variantMiceTitle,
    KolkhozText.variantNomenklaturaDescription =>
      strings.variantNomenklaturaDescription,
    KolkhozText.variantNomenklaturaTitle => strings.variantNomenklaturaTitle,
    KolkhozText.variantNorthernStyleDescription =>
      strings.variantNorthernStyleDescription,
    KolkhozText.variantNorthernStyleTitle => strings.variantNorthernStyleTitle,
    KolkhozText.variantOrdenNachalnikuDescription =>
      strings.variantOrdenNachalnikuDescription,
    KolkhozText.variantOrdenNachalnikuTitle =>
      strings.variantOrdenNachalnikuTitle,
    KolkhozText.variantPassCardsDescription =>
      strings.variantPassCardsDescription,
    KolkhozText.variantPassCardsTitle => strings.variantPassCardsTitle,
    KolkhozText.variantSwapDescription => strings.variantSwapDescription,
    KolkhozText.variantSwapTitle => strings.variantSwapTitle,
    KolkhozText.variantWreckerDescription => strings.variantWreckerDescription,
    KolkhozText.variantWreckerTitle => strings.variantWreckerTitle,
  };
}
