import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'package:kolkhoz_app/src/app/views/shared/world_depth_camera.dart';

export 'world_depth_camera.dart' show WorldDepthStop;

const worldDepthManifestAssetPath =
    'assets/art/field_plan/world_depth/manifest.json';

@immutable
class WorldDepthLayer {
  const WorldDepthLayer({
    required this.id,
    required this.name,
    required this.nodeId,
    required this.worldZ,
    required this.assetPath,
    required this.initialRect,
  });

  final String id;
  final String name;
  final String nodeId;
  final double worldZ;
  final String assetPath;
  final Rect initialRect;

  factory WorldDepthLayer.fromJson(Map<String, Object?> json) {
    final rect = _numberList(json, 'initialRect', length: 4);
    return WorldDepthLayer(
      id: _string(json, 'id'),
      name: _string(json, 'name'),
      nodeId: _string(json, 'nodeId'),
      worldZ: _number(json, 'worldZ'),
      assetPath: _string(json, 'assetPath'),
      initialRect: Rect.fromLTWH(rect[0], rect[1], rect[2], rect[3]),
    );
  }
}

@immutable
class WorldDepthManifest {
  const WorldDepthManifest({
    required this.viewportSize,
    required this.initialCameraZ,
    required this.focalLength,
    required this.vanishingPoint,
    required this.stops,
    required this.layers,
  });

  final Size viewportSize;
  final double initialCameraZ;
  final double focalLength;
  final Offset vanishingPoint;
  final List<WorldDepthStop> stops;
  final List<WorldDepthLayer> layers;

  factory WorldDepthManifest.fromJson(Map<String, Object?> json) {
    final schemaVersion = _number(json, 'schemaVersion').toInt();
    if (schemaVersion != 1) {
      throw FormatException(
        'Unsupported world depth manifest schema $schemaVersion.',
      );
    }

    final viewport = _map(json, 'viewport');
    final camera = _map(json, 'camera');
    _validateCameraContract(viewport, camera);
    final stops = worldDepthCameraCalibration.stops;
    final layers = _mapList(
      json,
      'layers',
    ).map(WorldDepthLayer.fromJson).toList();

    if (stops.isEmpty) {
      throw const FormatException('World depth manifest has no camera stops.');
    }
    if (layers.isEmpty) {
      throw const FormatException('World depth manifest has no layers.');
    }
    // Figma child order is the painter order for registered art plates. The
    // road-to-station-to-rail corridor is generated by WorldDepthScene.

    return WorldDepthManifest(
      viewportSize: Size(
        worldDepthCameraCalibration.viewportWidth,
        worldDepthCameraCalibration.viewportHeight,
      ),
      initialCameraZ: worldDepthCameraCalibration.startZ,
      focalLength: worldDepthCameraCalibration.focalLength,
      vanishingPoint: Offset(
        worldDepthCameraCalibration.vanishingPointX,
        worldDepthCameraCalibration.vanishingPointY,
      ),
      stops: stops,
      layers: layers,
    );
  }

  static Future<WorldDepthManifest> load({
    AssetBundle? bundle,
    String assetPath = worldDepthManifestAssetPath,
  }) async {
    final source = await (bundle ?? rootBundle).loadString(assetPath);
    final decoded = jsonDecode(source);
    if (decoded is! Map<String, Object?>) {
      throw const FormatException(
        'World depth manifest root must be an object.',
      );
    }
    return WorldDepthManifest.fromJson(decoded);
  }
}

void _validateCameraContract(
  Map<String, Object?> viewport,
  Map<String, Object?> camera,
) {
  final contract = worldDepthCameraCalibration;
  if (_string(camera, 'status') != contract.status) {
    throw const FormatException(
      'Generated world depth manifest has stale camera contract status.',
    );
  }
  void expectNumber(Map<String, Object?> json, String key, double expected) {
    if ((_number(json, key) - expected).abs() > 0.000001) {
      throw FormatException(
        'Generated world depth manifest has stale "$key" calibration.',
      );
    }
  }

  expectNumber(viewport, 'width', contract.viewportWidth);
  expectNumber(viewport, 'height', contract.viewportHeight);
  expectNumber(camera, 'initialZ', contract.startZ);
  expectNumber(camera, 'terminalZ', contract.terminalZ);
  expectNumber(camera, 'focalLength', contract.focalLength);
  expectNumber(camera, 'pitchDegrees', contract.pitchDegrees);
  expectNumber(camera, 'yawDegrees', contract.yawDegrees);
  expectNumber(camera, 'nearPlane', contract.nearPlane);
  expectNumber(camera, 'minimumScale', contract.minimumScale);
  expectNumber(camera, 'maximumScale', contract.maximumScale);
  expectNumber(camera, 'plateExitDistance', contract.plateExitDistance);
  final vanishingPoint = _numberList(camera, 'vanishingPoint', length: 2);
  if ((vanishingPoint[0] - contract.vanishingPointX).abs() > 0.000001 ||
      (vanishingPoint[1] - contract.vanishingPointY).abs() > 0.000001) {
    throw const FormatException(
      'Generated world depth manifest has a stale vanishing point.',
    );
  }
  final stops = _mapList(camera, 'stops');
  if (stops.length != contract.stops.length) {
    throw const FormatException(
      'Generated world depth manifest has stale camera stops.',
    );
  }
  for (var index = 0; index < stops.length; index++) {
    final actual = stops[index];
    final expected = contract.stops[index];
    if (_string(actual, 'id') != expected.id ||
        _string(actual, 'label') != expected.label ||
        (_number(actual, 'z') - expected.z).abs() > 0.000001) {
      throw FormatException(
        'Generated world depth manifest has a stale stop at index $index.',
      );
    }
  }
}

Map<String, Object?> _map(Map<String, Object?> json, String key) {
  final value = json[key];
  if (value is! Map<String, Object?>) {
    throw FormatException('Expected "$key" to be an object.');
  }
  return value;
}

List<Map<String, Object?>> _mapList(Map<String, Object?> json, String key) {
  final value = json[key];
  if (value is! List) {
    throw FormatException('Expected "$key" to be a list.');
  }
  return value.map((item) {
    if (item is! Map<String, Object?>) {
      throw FormatException('Expected every "$key" item to be an object.');
    }
    return item;
  }).toList();
}

List<double> _numberList(
  Map<String, Object?> json,
  String key, {
  required int length,
}) {
  final value = json[key];
  if (value is! List || value.length != length) {
    throw FormatException('Expected "$key" to contain $length numbers.');
  }
  return value.map((item) {
    if (item is! num) {
      throw FormatException('Expected every "$key" value to be a number.');
    }
    return item.toDouble();
  }).toList();
}

String _string(Map<String, Object?> json, String key) {
  final value = json[key];
  if (value is! String || value.isEmpty) {
    throw FormatException('Expected "$key" to be a non-empty string.');
  }
  return value;
}

double _number(Map<String, Object?> json, String key) {
  final value = json[key];
  if (value is! num) {
    throw FormatException('Expected "$key" to be a number.');
  }
  return value.toDouble();
}
